title: Edimoon's Blog
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/junghomoon" # the subpath of your site, e.g. /blog
url: "https://edimoon777.github.io/junghomoon" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Edimoon # add your name
author-img: edimoon.jpg # add your photo
about-author: I am a flight software engineer focusing on intelligent flight software. Always hungry to keep learning. # add description
social-twitter: # add your Twitter handle
social-facebook: Tigerjhmoon # add your Facebook handle
social-github: edimoon777 # add your Github handle
social-linkedin: jungho-moon-03aa06b0 # add your Linkedin handle
social-email: tigerjhmoon@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
